/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#414755",
        "on-secondary": "#ffffff",
        "surface-dim": "#dad9df",
        "tertiary-fixed": "#e2dfff",
        "tertiary-container": "#6664e4",
        "surface-tint": "#005bc1",
        "surface-variant": "#e3e2e7",
        "on-secondary-container": "#fffbff",
        "primary": "#0058bc",
        "surface": "#faf9fe",
        "background": "#faf9fe",
        "primary-container": "#0070eb",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004493",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#0c006a",
        "on-tertiary-container": "#fffbff",
        "secondary": "#bc000a",
        "secondary-container": "#e2241f",
        "on-primary-container": "#fefcff",
        "inverse-surface": "#2f3034",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3631b4",
        "tertiary": "#4c4aca",
        "surface-bright": "#faf9fe",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#1a1b1f",
        "outline": "#717786",
        "surface-container": "#eeedf3",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#ffb4aa",
        "on-secondary-fixed": "#410001",
        "on-primary-fixed": "#001a41",
        "on-error-container": "#93000a",
        "on-surface": "#1a1b1f",
        "secondary-fixed": "#ffdad5",
        "surface-container-highest": "#e3e2e7",
        "outline-variant": "#c1c6d7",
        "inverse-on-surface": "#f1f0f5",
        "surface-container-low": "#f4f3f8",
        "error-container": "#ffdad6",
        "surface-container-high": "#e9e7ed",
        "tertiary-fixed-dim": "#c2c1ff",
        "inverse-primary": "#adc6ff",
        "on-secondary-fixed-variant": "#930005",
        "on-tertiary": "#ffffff",
        // Additional colors from DESIGN.md
        "electric-blue": "#007AFF",
        "vivid-coral": "#FF3B30",
        "off-white": "#F5F5F7"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "md": "24px",
        "sm": "12px",
        "base": "8px",
        "xs": "4px",
        "lg": "48px",
        "xl": "80px"
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-display": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
